apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: postgres-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: postgres-postgresql.database.svc.cluster.local
    database.port: 5432
    database.user: postgres
    # CRITICAL: Reading password from the NEW /mnt location
    database.password: "${file:/mnt/postgres-auth/password:password}"
    database.dbname: postgres
    topic.prefix: postgres
    table.include.list: public.users
