apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: kafka
type: Opaque
stringData:
  password: "password123" # Matches your seed scripts
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: kafka
type: Opaque
stringData:
  password: "password123"
